package.json
src/scss/partials/_nav.scss

v0.10.0 — Added is-open state style.

---

.babelrc
CHANGELOG.md
package.json
yarn.lock

- Replaced babel ES2015 preset with env preset.

V0.11.2 — Replacing babel ES2015 preset with env preset.

---

CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_languageSwitcher.scss
src/scss/partials/_skipTo.scss
src/scss/partials/_skipToMain.scss

Add new sass file to cover the 'skip to main' element, and set its margin to 4px.

Skip to main content margin

---

CHANGELOG.md
package.json
yarn.lock

- Updated `browserslist`
- Updated package dependencies (minor updates)

v0.14.0 - Updating `browserslist`

---

CHANGELOG.md
package.json
src/templates/header/index.hbs
src/templates/header/partials/nav-alternate-language-links.hbs
src/templates/resources/header.json

- Renamed alternate language links partial.
- Fixed variable name for alternate language links.

v0.16.0 — Alternate language partial updates.

---

CHANGELOG.md
package.json

I tagged a pre-release which meant that v0.20.0 couldn't publish. Bumped the version for now and will look into how to release beta packages!

v0.20.1 - Version bump.

---

CHANGELOG.md
package.json
src/templates/header/partials/language-switcher.hbs
src/templates/header/partials/nav-alternate-language-links.hbs

- Updated alternative language url property name.

v0.20.5 — Updated alternative language url property name.

---

CHANGELOG.md
package.json
src/templates/resources/header-docs-data.json

- Removed links and unnecessary properties from docs data.

v0.21.3 — Removed links and unnecessary properties from docs data.

---

CHANGELOG.md
package.json
src/templates/resources/header-docs-data.json
src/templates/resources/header.json

v0.22.1 - Fix language switcher text in docs

---

CHANGELOG.md
package.json
src/templates/header/partials/language-switcher.hbs

Do not show info bar when not multi-tenant

 Render language-switcher partial based on `isMultiLingual` flag

---

CHANGELOG.md
package.json
yarn.lock

- Updating package dependencies

v0.27.0 – Updating package dependencies

---

CHANGELOG.md
dangerfile.js
package.json

v0.28.0 — Updated DangerJS config.

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_languageSwitcher.scss
src/scss/partials/_nav.scss
src/templates/header/partials/language-switcher.hbs

- Peer dependency to `f-icons` added to `package.json`
- Chevron icon in language switcher now inlined using inlineSVG helper
- Tidied up some class names in the language switcher
- The body container now doesn't jump around when the menu is opened.
- The navigation height is correct when multi language versions of the site are viewed (it menu previously overlapped the header when open).
- Fixed persistent scrollbar which was visible on narrow viewports.
---
---
---

v0.32.0 - Fixing language switcher and mobile bugs to nav

---

CHANGELOG.md
package.json
src/scss/index.scss

_Update header button and remove border._
- Fixed positioning on `c-header-button`.
- Changed targetting on `c-header-buttonIcon` SVG to apply fill.
- Updates `c-header` border.
- Bump of f-icons
Before:
After:

v0.36.0 - Update header button and remove border

---

CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_nav.scss
src/templates/header/index.hbs
src/templates/resources/header-docs-data.json

- Header `z-index` value updated so that it displays above elements.
- Transparent header nav text link colour should always be white.
- Header CSS class variable to template.

v0.39.0 — Header style fixes.

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

- Fix z-index on header button

v0.41.0 - Fix z-index on header button

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

- remove duplicate SCSS variable

v0.47.1 - remove duplicate variable

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_nav.scss
yarn.lock

- Removed gradient effect from `c-header--gradient`. Added the new `c-header--gradient` class for gradient effect.
- Added transparency to the header icon.

v1.0.0 - Made gradient effect of header navigation optional

---

CHANGELOG.md
package.json
src/scss/partials/_logo.scss

v1.0.1 Fixed Menulog logo

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

__*This is the standard PR description template.*__
---
_Added css for a secondary button on the right hand sight of the header._
(url)

v1.8.0 - Header button positions

---

CHANGELOG.md
package.json
src/templates/resources/header-docs-data.json
src/templates/resources/header.json

Add links ready for the UK launch of gift cards redemption site.

v1.9.0 - added giftcards link

---

CHANGELOG.md
package.json
src/templates/resources/header-docs-data.json

Small change to fix broken global component library.

v1.11.1 - Added redeem giftcard to header docs to fix global component library

---

.travis.yml
CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_nav.scss
src/templates/resources/header.json
yarn.lock

Brand updates for Menulog.
Lots of lines in the yarn.lock file, which is the correct registry? @ashleynolan

v1.16.0 - Menulog brand updates

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_logo.scss
src/scss/partials/_nav.scss
yarn.lock

... and use fozzie colour variables where possible

v1.18.0 - Resizing new logo

---

CHANGELOG.md
package.json
src/scss/partials/_logo.scss

Fixing the logo sizing now that I have the designs.
Recommend hiding whitespace changes when reviewing the CSS file.

v1.19.0 - Logo size tweaks

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

v1.21.0 - Update nav icon colour for Menulog

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

Update nav icon colour from orange to blue.

v1.25.1 - Update nav toggle icon colour

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_infoBar.scss
src/scss/partials/_nav.scss
yarn.lock

- Updated font variables to work in-line with new font updates.
- Needs Image from testing.

v1.28.0 – Updating font variables in line with fozzie update

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

- Updating nav links to be bold (`font-weight: 600`).

v1.29.0 – Updating link font-weight to bold

---

CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_header.scss
src/scss/partials/_infoBar.scss
src/scss/partials/_languageSwitcher.scss
src/scss/partials/_logo.scss
src/scss/partials/_nav.scss
src/scss/partials/_skipTo.scss
yarn.lock

- Updating legacy component to be compatible with Fozzie v5.

f-header@v1.30.0 – Updating to use fozzie v5

---

CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_logo.scss
yarn.lock

- fozzie to the latest version (6.2.0).
- theme mixin and theme styles as outdated.

v1.33.0 - remove theme styles

---

package.json

v1.33.0 - remove theme styles (#133)

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_nav.scss

v1.34.0
------------------------------
*April 19, 2022*
- `_header.scss` & `_nav.scss` to updated header version.

f-header@v1.34.0 - Updated _header.scss & _nav.scss to updated header version.
