justeat/f-header

.travis.yml
CHANGELOG.md
dangerfile.js
package.json
test/index.test.js
yarn.lock

- `dangerfile.js` added to check PRs via Travis
- Updated `gulp-build-fozzie` and `fozzie-colour-palette` versions
- Updated `js-test-buddy` and associated test references

v0.12.0 - Adding dangerfile and updating test references

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

v0.20.4 -- position fixed the body element when mobile navigation iniew as background content scrollable in iOS devices

v0.20.4 -- position fixed the body element when mobile navigation in view 

---

CHANGELOG.md
package.json
src/templates/resources/header.json

Change link text for `contactPreferences` to match UK production.

v0.21.2 - Fix incorrect link text

---

CHANGELOG.md
package.json
src/templates/header/index.hbs

Looks like adding if/else statement is not an optimal way to do this change, but conditional syntax 
`target="{{if isHelpExternal "_blank"}}"` didn't work...
https://guides.emberjs.com/v3.0.0/templates/conditionals/

0.23.0 - Conditional "target=_blank" for the help menu link

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

The header navigation used to be 16px some changes I made in fozzie caused the navigation font size to increase. I've added a new property to our `$type` map to fix this.

v0.25.0 : Changed nav font size to base--scaleUp size.

---

CHANGELOG.md
README.md
package.json
yarn.lock

- rimraf dev dependency.
- Script to clean the `dist` directory before transpiling code which runs before compile script.
- Prevent adding unit test files to the `dist` directory.
- Removed the gemnasium badge from the readme.

v0.29.0 — Improving the compile script.

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

__*update of burger icon for consistency with f-icons*__
Before:
After:

v0.34.0 - update of burger icon for consistency with f-icons

---

CHANGELOG.md
package.json
src/templates/resources/header.json

This PR adds pseudo-localised English for `qps-ploc` to allow localisation testing on Windows ([docs](https://docs.microsoft.com/en-us/windows/desktop/intl/using-pseudo-locales-for-localization-testing)).
Values were generated using my custom fork of [anderskaplan/Pseudolocalizer](https://github.com/anderskaplan/Pseudolocalizer):
https://github.com/martincostello/Pseudolocalizer/tree/xliff-support

v0.35.0 - Add qps-ploc resources

---

.travis.yml
CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_header.scss
src/scss/partials/_languageSwitcher.scss
src/scss/partials/_nav.scss
yarn.lock

- Moved base header styles into `_header.scss` file for better separation
- Changed utils dependencies onto `@justeat/f-utils` module rather than using `kickoff/utils`
- Updated package dependencies

v0.40.0 – Rearranging styles and updating onto f-utils package

---

.babelrc
.travis.yml
CHANGELOG.md
LICENSE
package.json
src/js/test/__snapshots__/index.test.js.snap
src/js/userAuth/index.js
src/scss/partials/_header.scss
src/scss/partials/_nav.scss
yarn.lock

- Added Menulog theme overrides that will be active when SCSS is compiled with `$theme: ml;`.
- Updated dependencies to use Babel 7
- Updated Snapshot files from previous commit (to fix snapshot tests)
---

v0.43.0 – Adding Menulog theme overrides

---

CHANGELOG.md
package.json
src/js/userAuth/userData.js
yarn.lock

- Travis build fixed by regenerating the yarn lock file.
- Lint parsing error fixed by adding "espree" resolution.
- Added `f-logger` to fix warnings about console logging in userData module.

v0.44.0 — Travis build fixed by regenerating the yarn lock file.

---

CHANGELOG.md
package.json
yarn.lock

- Babel config and packages removed from module as now added by `gulp-build-fozzie`.
- Unfortunately cannot remove the `espree` resolution due to this needing to be locked down on a per package basis.

v0.45.0 – Removing Babel config from module (and small package updates)

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

- Changed `z-index` on `c-header-button` to `high - 1` to stop elm showing when popover components are active
Before:
After:

v0.46.0 - update of zindex on c-header-button

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

- addition of styles for `c-header-buttonCount`

v0.47.0 - addition of styles for `c-header-buttonCount`

---

CHANGELOG.md
package.json
src/scss/partials/_logo.scss

- Fixed Menulog logo positioning. Also removed the logo outline in transparent mode so if background colour changes we won't need to update the logo. 
here are the screenshot in different states:

v1.0.2 Fixed menulog logo

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss

- Update `c-headerButton` position and touch area
Before:
After:

v1.1.0 - Update `c-headerButton` position and touch area

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss

Fixed invisible text when hovering over header menu
Before:
After:

v1.1.1 Fix invisible text when hovering over header menu

---

CHANGELOG.md
package.json
src/templates/header/index.hbs
src/templates/resources/header-docs-data.json

Add the appropriate classes for transparent header when the `useTransparentHeader` flag is passed up from the back-end.

v1.2.0 - Transparent header support

---

CHANGELOG.md
package.json
src/scss/partials/_header.scss
src/scss/partials/_logo.scss
yarn.lock

Patching last release. It was missing the babel-core resolution which caused the tests to fail (but `npm publish` still succeeded..?).

v1.2.1 - Add babel-core resolution

---

CHANGELOG.md
package.json
src/scss/partials/_skipTo.scss
src/templates/header/index.hbs
src/templates/header/partials/skip-to.hbs
src/templates/resources/header.json

- 'loginLinkText' from 'Log-in' to 'Log in'
- `c-skipTo` style amends

v1.3.0 Change login link text + c-skipTo styles amends

---

CHANGELOG.md
package.json
src/js/index.js
src/js/test/__snapshots__/index.test.js.snap
src/js/test/index.test.js
src/scss/partials/_logo.scss
src/scss/partials/_nav.scss
src/templates/header/index.hbs

- Fixed issue with `is-navInView` class not being applied to narrow header element to stop scrolling of the page.  Also has to add new `is-navInView--noPad` to allow for transparent/fixed headers.

v1.5.0 - `is-navInView` class fix

---

CHANGELOG.md
package.json
src/templates/header/index.hbs

This PR provides an update which ensures links to the login page across the shared header have the rel="nofollow" html attribute, which should help to resolve an SEO related issue reported to the team.
- No visual changes made

v1.5.1 - Update Header to add 'rel="nofollow" to login page links

---

CHANGELOG.md
package.json
src/js/index.js
src/js/test/index.test.js
src/templates/header/index.hbs

- Add a check to make sure that hamburger menu is closed when the user navigates back to the page

v1.7.0 check for hamburger menu to be closed by default

---

CHANGELOG.md
package.json
src/scss/partials/_nav.scss
src/templates/header/index.hbs

Long user names can potentially break the header layout, so the text overflow needs to be added to allow longer names without breaking the layout.
Before:
After:

v1.7.1 - Add text overflow ellipsis to better display long user names

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
package.json
src/templates/resources/header.json

MENU-3213: Inserts missing translation string for en-GB
No markup/styling changed - used to fix error due to missing string when generating handlebars templates

v1.11.2 - MENU-3213: Inserts missing translation string for en-GB

---

CHANGELOG.md
package.json
src/scss/partials/_logo.scss

v1.13.1 - Fixed an issue where the logo disapears on MenuWeb
The issue was introduced in 1.13.0, caused by a change to the selector which applies styles to set the logo size. MenuWeb uses an SVG, and the selector was changed to target only IMG.
This PR simply selects both `c-logo-img img, c-logo-img svg`.
Before
Now

v1.13.1 - Fixed an issue where the logo disapears on MenuWeb

---

CHANGELOG.md
package.json
yarn.lock

`v1.68.0` of `@justeat/fozzie` breaks the styling of the cuisine grid, and the unpinned version here allows our components to pull in the latest versions of the header when the `yarn.lock` is regenerated from scratch.

v1.14.0 - Pin `@justeat` package versions

---

CHANGELOG.md
package.json
yarn.lock

v1.31.0
------------------------------
*August 27, 2021*
- Updating legacy component to be compatible with Fozzie v6.

f-header@v1.31.0 - Update fozzie to v6 beta

---

CHANGELOG.md
README.md
package.json
src/scss/index.scss

- Removed utility call as it causes issues when pulled in alongside fozzie in legacy sites. Added note to README for including utility classes.

v1.36.0 – Removing trumps from dependencies
